// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkG_J1EAMOpO48PU9y0fAwb8WYuSY3EKQ',
    appId: '1:825357136296:web:6b111571a48f5bca5ded9d',
    messagingSenderId: '825357136296',
    projectId: 'chatting-app-8d39c',
    authDomain: 'chatting-app-8d39c.firebaseapp.com',
    storageBucket: 'chatting-app-8d39c.firebasestorage.app',
    measurementId: 'G-ECWZDZS7N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2q74PW-b6_EOfo9cmDugBhTvmp_5Ub9A',
    appId: '1:825357136296:android:54732873c7d4765d5ded9d',
    messagingSenderId: '825357136296',
    projectId: 'chatting-app-8d39c',
    storageBucket: 'chatting-app-8d39c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2OsqGv5v_1Qbif6tRpRStNExMD5JkaI0',
    appId: '1:825357136296:ios:e634247a89ab4a025ded9d',
    messagingSenderId: '825357136296',
    projectId: 'chatting-app-8d39c',
    storageBucket: 'chatting-app-8d39c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2OsqGv5v_1Qbif6tRpRStNExMD5JkaI0',
    appId: '1:825357136296:ios:e634247a89ab4a025ded9d',
    messagingSenderId: '825357136296',
    projectId: 'chatting-app-8d39c',
    storageBucket: 'chatting-app-8d39c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkG_J1EAMOpO48PU9y0fAwb8WYuSY3EKQ',
    appId: '1:825357136296:web:abfc7a6211764d1e5ded9d',
    messagingSenderId: '825357136296',
    projectId: 'chatting-app-8d39c',
    authDomain: 'chatting-app-8d39c.firebaseapp.com',
    storageBucket: 'chatting-app-8d39c.firebasestorage.app',
    measurementId: 'G-3CKMBK1PS8',
  );
}
